/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.guilford.finalprojecthomescreen;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author tgolla
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    
    private Image wallpaper;
    
        
    public HomePanel() {
        initComponents();
        ImageIcon paintIcon = new ImageIcon(HomePanel.class.getResource("/paintafter.png"));
        Image iconImage = paintIcon.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT);
        paintIcon = new ImageIcon(iconImage);
        paintButton.setIcon(paintIcon);
        // Instantiating an ImageIcon object that holds the image
        ImageIcon homeBackground = new ImageIcon(HomePanel.class.getResource("/macbookdesertwallpaper.jpeg"));
        // Get the image file from homeBackground and set it to the Image object instantiated earlier
        this.wallpaper = homeBackground.getImage().getScaledInstance(1280, 800,Image.SCALE_DEFAULT);
        
        ImageIcon userIcon = new ImageIcon(HomePanel.class.getResource("/userprofile.png"));
        Image profileImage = userIcon.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT);
        userIcon = new ImageIcon(profileImage);
        userProfileButton.setIcon(userIcon);
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.drawImage(wallpaper, 0, 0, this);
        paintButton.setLocation(600, 600);
        userProfileButton.setLocation(667,600);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paintButton = new javax.swing.JButton();
        userProfileButton = new javax.swing.JButton();

        paintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintButtonActionPerformed(evt);
            }
        });

        userProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(paintButton)
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userProfileButton)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(userProfileButton)
                .addGap(98, 98, 98)
                .addComponent(paintButton)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void paintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintButtonActionPerformed
        // TODO add your handling code here:
        JFrame ellipsedraw = new JFrame("Ellipse");
        
        //add a panel to the window
        EllipsePanel ePanel = new EllipsePanel();
        ellipsedraw.getContentPane().add(ePanel);
        
        ellipsedraw.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ellipsedraw.pack();
        ellipsedraw.setVisible(true);
        
    }//GEN-LAST:event_paintButtonActionPerformed

    private void userProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfileButtonActionPerformed
        // TODO add your handling code here:
        JFrame userInfo = new JFrame("User Information");
        
        userPanel uPanel = new userPanel();
        userInfo.getContentPane().add(uPanel);
        
        userInfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        userInfo.pack();
        userInfo.setVisible(true);
        
    }//GEN-LAST:event_userProfileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton paintButton;
    private javax.swing.JButton userProfileButton;
    // End of variables declaration//GEN-END:variables
}
